//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetArchi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archives
    {
        public int id_archive { get; set; }
        public int xid_proj { get; set; }
        public byte[] Images { get; set; }
        public byte[] fichiers { get; set; }
        public int xid_personnes { get; set; }
    
        public virtual Personnes Personnes { get; set; }
        public virtual Projets Projets { get; set; }
    }
}
