//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetArchi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireCréationProjet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionnaireCréationProjet()
        {
            this.RéponsesQuestionnaireProjet = new HashSet<RéponsesQuestionnaireProjet>();
        }
    
        public int idQuest { get; set; }
        public int xidClient { get; set; }
        public int xidProjet { get; set; }
        public string Question { get; set; }
        public bool Checked { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RéponsesQuestionnaireProjet> RéponsesQuestionnaireProjet { get; set; }
        public virtual Projets Projets { get; set; }
    }
}
